#include <iostream>
using namespace std;
int main(){
    try {
        throw 10;
    }
        catch (char *excp) {
        cout << "Capturado " << excp;
    }
    catch (...) {
        cout << "ExcepciÃ³n por defecto\n";
    }
    return 0;
}